name: evdb-databases

volumes:
  mssql:
  psql:
  mongodb_data:
  dbeaver_data:
  # mssqllatin:
  # mysql:
  # mysql5:
  # mysql8:
  # psql96:
  # psql13:
  # mariadb:
  # cockroachdb:
  # bigquery:

services:

  sqlserver:
    container_name: sqlserver-event-source
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "MasadNetunim12!@"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    # command: sh -c ' chmod +x /docker_init/entrypoint.sh; /docker_init/entrypoint.sh & /opt/mssql/bin/sqlservr;'
    restart: unless-stopped
    networks:
      - database-network
    
  psql:
    container_name: psql-event-source
    image: postgres:latest
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: MasadNetunim12!@
      POSTGRES_DB: test_db
    volumes:
      - psql:/var/lib/postgresql/data
      - ./dev/docker_psql_init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - database-network
    
  mongodb:
    image: mongo:8
    container_name: mongodb-event-source
    volumes:
      - mongodb_data:/data/db
    environment:
      #  MONGO_INITDB_ROOT_USERNAME: rootuser
      #  MONGO_INITDB_ROOT_PASSWORD: MasadNetunim12!@
      MONGO_INITDB_DATABASE: evdb
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    ports:
      - "27017:27017"
    command: "--bind_ip_all --quiet --logpath /dev/null --replSet rs0"
    restart: unless-stopped
    networks:
      - database-network
    
  mongo-init:
    image: mongo:8
    container_name: mongodb-event-source-init
    depends_on:
      mongodb:
        condition: service_healthy
    command: >
      mongosh --host mongodb:27017 --eval
      '
      rs.initiate( {
         _id : "rs0",
         members: [
            { _id: 0, host: "localhost:27017" }
         ]
      })
      '
    restart: no
    networks:
      - database-network

  dbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: dbeaver
    volumes:
      - dbeaver_data:/opt/cloudbeaver/workspace
      - ./dbeaver-init/initial-data.conf:/opt/cloudbeaver/workspace/initial-data.conf
    ports:
      - "8978:8978"
    depends_on:
      - sqlserver
      - psql
    restart: unless-stopped
    networks:
      - database-network

networks:
  database-network:
    driver: bridge